### ISSUE TITLE
J2010 date wrong?

### ISSUE THREAD

**Issue by duairc** [Alexander-Ignatyev/astro#4]
Hi,

In `Data.Astro.Time.Epoch`, `j2010` is defined as follows:

    j2010 :: JulianDate
    j2010 = JD 2455196.5

I might be completely wrong, I'm very new to astronomy, but is this not off by one? Because 2455196.5 is 31 December 2009 00:00 UTC. Should it not be `2455197.5`?

**Comment by aligusnet** [comment]
If we take J2000 (12h on 1 January 2000) as reference point which is 2451545.0.
2451545.0 - 0.5 (for 12h) + 365 * 10 + 3 (three leap days - 2000, 2004, 2008) = 2455197.5
Looks like you are correct.

**Comment by duairc** [comment]
Given that all the `{Sun,Planet,Moon}Details` are given with respect to J2010, are they wrong too then? I don't know where you got them from — did you calculate them yourself with reference to your "J2010", or were they given in a book somewhere for reference with the real J2010? If the former, then you would have to recalculate them if you fixed j2010, if the latter then fixing j2010 will make things more accurate.

**Comment by aligusnet** [comment]
Actually, J2010 is `2455196.5`.

Because J2010 is 2010 January 0.0. 0th January and J2000 is 2000 1.5th January. So the difference between them is

2451545.0 - 1.5 (for 1.5 days) + 365 * 10 + 3 (three leap days - 2000, 2004, 2008) = 2455196.5.

I have checked with the Practical astronomy by Peter Duffett-Smith book.

Technically speaking 0 January 2010 is 31 December 2009 for we count days from 1, not 0.

**Comment by aligusnet** [comment]
> Given that all the {Sun,Planet,Moon}Details are given with respect to J2010, are they wrong too then? I don't know where you got them from — did you calculate them yourself with reference to your "J2010", or were they given in a book somewhere for reference with the real J2010? 

I referenced all these data from Practical astronomy by Peter Duffett-Smith. The same source that states J2010 is 2455196.5.

So all the params should be fine.

**Comment by duairc** [comment]
Okay, great, thanks for clearing that up, sorry for the noise!

**Comment by aligusnet** [comment]
No worries, thank you for the report.
